jobs:
  os-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and test
        run: |
          sh build_test.sh
      - name: Upload test results for review
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ runner.os }}-mvn-v${{ matrix.mvn }}-jvm${{ matrix.java }}
          path: |
            target/build.log
          retention-days: 5

  maven-version-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mvn: ['3.9.8', '3.8.8', '3.6.3']
        java: ['11']
        include:
          - mvn: '3.9.8'
            java: '21'
          - mvn: '3.8.8'
            java: '17'
          - mvn: '3.6.3'
            java: '11'
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Set up maven wrapper for specified version
        run: |
          mvn wrapper:wrapper -Dmaven=${{ matrix.mvn }}
      - name: Build and test
        run: |
          sh build_test.sh
      - name: Upload test results for review
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-mvn-v${{ matrix.mvn }}-jvm${{ matrix.java }}
          path: |
            target/build.log
          retention-days: 5
