name: Java CI with Maven
on: [ push, pull_request, workflow_dispatch ]

jobs:
  os-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build and test
        run: |
          mvn -B install -f j2cl-maven-plugin/pom.xml
      - name: Upload test results for review
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-mvn-v3.8.8-jvm17
          path: |
            target/build.log
          retention-days: 5
